apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --k8s-allow-namespace=dev
            - --manifest-generation=true
            - --memcached-service=
            - --git-poll-interval=1m
            - --sync-interval=1m
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-url=git@github.com:stefanprodan/flux-upgrade-test
            - --git-branch=stg
            - --git-path=
