apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagger
spec:
  template:
    spec:
      containers:
        - name: flagger
          command:
            - ./flagger
            - -log-level=info
            - -mesh-provider=kubernetes
            - -metrics-server=http://flagger-prometheus:9090
            - -namespace=""
            - -slack-user=flagger
            - -slack-channel=""
            - -slack-url=""
