---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: demo
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: podinfo-test
  chart:
    git: git@github.com:stefanprodan/flux-upgrade-test
    path: charts/podinfo
    ref: master
  values:
    image: stefanprodan/podinfo:1.3.1
