---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: podinfo
  namespace: demo
  annotations:
    flux.weave.works/automated: "false"
spec:
  chartGitPath: podinfo
  releaseName: podinfo-test
  values:
    image: stefanprodan/podinfo:0.4.0
