namespace: flagger-system
commonLabels:
  app: flagger
resources:
  - namespace.yaml
  - account.yaml
  - rbac.yaml
  - crd.yaml
  - deployment.yaml
images:
  - name: weaveworks/flagger
    newTag: 0.16.0
