apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "false"
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: memcached:1.5.15
          imagePullPolicy: IfNotPresent
          args:
            - -m 512    # Maximum memory to use, in megabytes. 64MB is default.
            - -p 11211    # Default port, but being explicit is nice.
            - -I 5m #  Maximum size for one item
          ports:
            - name: memcached
              containerPort: 11211
          resources:
            requests:
              memory: 120Mi
              cpu: 50m
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 11211
            runAsUser: 11211

---
apiVersion: v1
kind: Service
metadata:
  name: memcached
spec:
  ports:
    - port: 11211
      targetPort: memcached
      protocol: TCP
      name: memcached
  selector:
    app: memcached

